import {
  OpportunityVerdict,
  AccessModel,
  PublicApiStatus,
  ApiStyle,
  ApiBreadth,
} from '../types/schema.js';

export interface VerdictInput {
  developer_access: {
    access_model: AccessModel;
    credentials_obtainable_without_human_approval: boolean | 'unknown';
    access_notes?: string;
  };
  api_surface: {
    public_api: PublicApiStatus;
    api_styles: ApiStyle[];
    api_breadth: ApiBreadth;
  };
}

export interface VerdictResult {
  verdict: OpportunityVerdict;
  primary_blocker: string | null;
  verdict_reasoning: string;
  is_provisional_rule: boolean;
}

/**
 * Provisional v1 Deterministic Verdict Engine.
 * 
 * Rules:
 * 1. public API ('no') -> blocked/low priority.
 * 2. partner_gated or sales_gated credentials -> outreach required (vendor approval required).
 * 3. admin_gated -> PROVISIONAL v1 rule:
 *    Distinguishes vendor approval from normal customer/workspace administrator authorization.
 *    If credentials require vendor/sales intervention, it is outreach_required.
 *    If normal workspace administrator can authorize API keys/OAuth apps directly without vendor contact,
 *    it is treated provisionally under build_with_caveats or build_now until calibration evidence is finalized.
 * 4. public API ('yes') + self-serve credentials (self_serve_free, self_serve_trial, self_serve_paid or credentials_obtainable_without_human_approval === true) -> build now (or build_with_caveats if API breadth is narrow/limited).
 * 5. unclear critical facts -> unclear.
 */
export function computeProvisionalVerdict(input: VerdictInput): VerdictResult {
  const { developer_access, api_surface } = input;

  // Rule 1: No documented public API
  if (api_surface.public_api === 'no') {
    return {
      verdict: 'blocked_low_priority',
      primary_blocker: 'No documented public API available.',
      verdict_reasoning:
        'Application lacks documented REST, GraphQL, or SDK endpoints required for agent tool calling.',
      is_provisional_rule: false,
    };
  }

  // Rule 5: Unclear critical facts regarding API availability
  if (api_surface.public_api === 'unclear' || developer_access.access_model === 'unclear') {
    return {
      verdict: 'unclear',
      primary_blocker: 'Research data ambiguous or insufficient.',
      verdict_reasoning:
        'Critical atomic facts regarding public API availability or credential gating remain unclear.',
      is_provisional_rule: false,
    };
  }

  // Rule 2: Partner gated or Sales gated (explicit vendor intervention required)
  if (developer_access.access_model === 'partner_gated') {
    return {
      verdict: 'outreach_required',
      primary_blocker: 'Requires formal ISV or partner program approval from vendor.',
      verdict_reasoning:
        'Public API endpoints exist, but developer credentials require formal legal/partner approval.',
      is_provisional_rule: false,
    };
  }

  if (developer_access.access_model === 'sales_gated') {
    return {
      verdict: 'outreach_required',
      primary_blocker: 'Access requires contacting enterprise sales team.',
      verdict_reasoning:
        'Public API endpoints exist, but developer credentials cannot be obtained without sales contact.',
      is_provisional_rule: false,
    };
  }

  // Rule 3: Admin Gated (PROVISIONAL V1 RULE)
  if (developer_access.access_model === 'admin_gated') {
    const notes = (developer_access.access_notes || '').toLowerCase();
    const requiresVendorApproval =
      notes.includes('vendor approval') ||
      notes.includes('contact support to enable') ||
      developer_access.credentials_obtainable_without_human_approval === false;

    if (requiresVendorApproval) {
      return {
        verdict: 'outreach_required',
        primary_blocker: 'Requires vendor/support approval for admin credentials.',
        verdict_reasoning:
          '[PROVISIONAL V1] Admin gated access explicitly requires external vendor authorization.',
        is_provisional_rule: true,
      };
    }

    return {
      verdict: 'build_with_caveats',
      primary_blocker: 'Requires workspace administrator authorization.',
      verdict_reasoning:
        '[PROVISIONAL V1] Credentials can be generated by a normal customer/workspace administrator without vendor sales intervention. Requires caveat regarding admin rights.',
      is_provisional_rule: true,
    };
  }

  // Rule 4: Self-serve access + public API
  const isSelfServeModel = [
    'self_serve_free',
    'self_serve_trial',
    'self_serve_paid',
  ].includes(developer_access.access_model);

  if (
    api_surface.public_api === 'yes' &&
    (isSelfServeModel || developer_access.credentials_obtainable_without_human_approval === true)
  ) {
    if (api_surface.api_breadth === 'narrow' || api_surface.public_api === 'limited') {
      return {
        verdict: 'build_with_caveats',
        primary_blocker: 'Limited or narrow API surface area.',
        verdict_reasoning:
          'Self-serve developer credentials exist and API is public, but surface area is narrow or limited.',
        is_provisional_rule: false,
      };
    }

    return {
      verdict: 'build_now',
      primary_blocker: null,
      verdict_reasoning:
        'Self-serve developer access is verified with a broad/moderate documented public API.',
      is_provisional_rule: false,
    };
  }

  // Fallback for edge cases where public API is limited/yes and access model is unknown/other
  if (developer_access.credentials_obtainable_without_human_approval === 'unknown') {
    return {
      verdict: 'unclear',
      primary_blocker: 'Unclear whether credentials can be obtained without human approval.',
      verdict_reasoning:
        'API is documented, but the exact self-serve path vs. human approval requirement remains unconfirmed.',
      is_provisional_rule: false,
    };
  }

  return {
    verdict: 'build_with_caveats',
    primary_blocker: 'Minor onboarding or tier restrictions.',
    verdict_reasoning:
      'Application is technically buildable, subject to specific account or tier constraints.',
    is_provisional_rule: true,
  };
}
